name: Run Python

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script
        run: python task.py

      - name: Save file2
        run: | 
          git config user.name "Eliza-bet88"
          git config user.email "vezunchikliza@gmail.com"
          git add file2.txt
          git commit -m "update file2" || true
          git push  
